[start]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json start
parameters:
type:script_output

[stop]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json stop
parameters:
type:script_output

[restart]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json restart
parameters:
type:script_output
description:Restart mihomo service

[status]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json status
parameters:
type:script_output

[wan-restart]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json wan-restart
parameters:
type:script_output

[enable-transparent]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json enable-transparent
parameters:
type:script_output

[disable-transparent]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json disable-transparent
parameters:
type:script_output

[sub-update]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json queue-update
parameters:
type:script_output
description:Renew mihomo Subscription

[set-settings]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json set-settings
parameters:%s
type:script_output

[save-config]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json save-config
parameters:%s
type:script_output

[clear-log]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json clear-log
parameters:
type:script_output

[save-merge]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json save-merge
parameters:%s
type:script_output

[load-preset]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json load-preset
parameters:%s
type:script_output

[clear-sub-log]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json clear-sub-log
parameters:
type:script_output

[devices]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json devices
parameters:
type:script_output

[repair-backup]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/mihomo/mihomo.py --json repair-backup
parameters:
type:script_output
message:Listing known devices
