[start]
command:sh /usr/local/etc/rc.d/os-lucky onestart
parameters:
type:script
message:starting lucky

[stop]
command:sh /usr/local/etc/rc.d/os-lucky onestop
parameters:
type:script
message:stopping lucky

[restart]
command:sh /usr/local/etc/rc.d/os-lucky onerestart
parameters:
type:script
message:restarting lucky
description:Restart Lucky service

[status]
command:sh /usr/local/etc/rc.d/os-lucky onestatus
parameters:
type:script_output
message:request lucky status

[get]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/lucky/settings.py get
parameters:
type:script_output
message:get lucky settings

[set]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/lucky/settings.py set
parameters:%s
type:script_output
message:set lucky settings
