[apply]
command:/usr/local/sbin/staticarpctl apply
parameters:
type:script_output
message:applying static ARP binding
description:Apply Static ARP Binding

[reset]
command:/usr/local/sbin/staticarpctl reset
parameters:
type:script_output
message:resetting static ARP binding
description:Reset Static ARP Binding

[status]
command:/usr/local/sbin/staticarpctl status
parameters:
type:script_output
message:request static ARP binding status
description:Static ARP Binding status

[get]
command:/usr/local/bin/php /usr/local/opnsense/scripts/staticarp/settings.php get
parameters:
type:script_output
message:get staticarp settings

[set]
command:/usr/local/bin/php /usr/local/opnsense/scripts/staticarp/settings.php set
parameters:%s
type:script_output
message:set staticarp settings

[script]
command:/usr/local/bin/php /usr/local/opnsense/scripts/staticarp/settings.php script
parameters:%s
type:script_output
message:generate Static ARP helper script
