[start]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/easytier/manage.py start
parameters:
type:script_output
message:easytier start

[stop]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/easytier/manage.py stop
parameters:
type:script_output
message:easytier stop

[restart]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/easytier/manage.py restart
parameters:
type:script_output
message:easytier restart

[status]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/easytier/manage.py status
parameters:
type:script_output
message:easytier status

[clear_log]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/easytier/manage.py clear_log
parameters:
type:script_output
message:easytier clear_log

[settings]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/easytier/manage.py settings
parameters:
type:script_output
message:easytier settings

[save]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/easytier/manage.py save
parameters:%s
type:script_output
message:easytier save

[peers]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/easytier/manage.py peers
parameters:
type:script_output
message:easytier peers

[log]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/easytier/manage.py log
parameters:
type:script_output
message:easytier log
