[start]
command:/usr/local/etc/rc.d/easytier onestart
parameters:
type:script
message:starting EasyTier

[stop]
command:/usr/local/etc/rc.d/easytier onestop
parameters:
type:script
message:stopping EasyTier

[restart]
command:/usr/local/etc/rc.d/easytier onerestart
parameters:
type:script
message:restarting EasyTier

[status]
command:/usr/local/etc/rc.d/easytier onestatus; exit 0
parameters:
type:script_output
message:request EasyTier status

[clear_log]
command:/usr/bin/truncate -s 0 /var/log/easytier.log
parameters:
type:script
message:clearing EasyTier log
