[start]
command:
    /usr/local/etc/rc.d/ddclient_opnwall_perl start &&
    /usr/local/etc/rc.d/ddclient_opn start
type:script
message:starting ddclient

[stop]
command:/usr/local/etc/rc.d/ddclient_opnwall_perl onestop && /usr/local/etc/rc.d/ddclient_opn onestop
type:script
message:stopping ddclient

[status]
command:/usr/local/sbin/pluginctl -s ddclient status
type:script_output
message:get ddclient status

[restart]
command:
    /usr/local/etc/rc.d/ddclient_opnwall_perl onestop &&
    /usr/local/etc/rc.d/ddclient_opn onestop &&
    /usr/local/etc/rc.d/ddclient_opnwall_perl start &&
    /usr/local/etc/rc.d/ddclient_opn start
type:script
message:restarting ddclient
description:Restart ddclient service

[force]
command:
    /usr/local/etc/rc.d/ddclient_opnwall_perl onestop &&
    /usr/local/etc/rc.d/ddclient_opn onestop &&
    /bin/rm -f /var/tmp/ddclient_opn.status &&
    /bin/sh -c 'result=0; if /usr/local/etc/rc.d/ddclient_opnwall_perl enabled; then /usr/local/bin/python3 /usr/local/opnsense/scripts/ddclient/perl_backend.py force || result=$?; fi; /usr/local/etc/rc.d/ddclient_opnwall_perl start && /usr/local/etc/rc.d/ddclient_opn start || exit $?; exit $result'
type:script
message:forcing ddclient update
description:Force ddclient update

[statistics]
command:/usr/local/opnsense/scripts/ddclient/stats
type:script_output
message:get ddclient statistics

[opnbackend.supported]
command:/usr/local/opnsense/scripts/ddclient/ddclient_opn.py -l
type:script_output
message:get ddclient statistics
