[start]
command:/usr/local/etc/rc.d/wanguard start
parameters:
type:script
message:starting WAN Guard
description:Start WAN Guard

[stop]
command:/usr/local/etc/rc.d/wanguard onestop
parameters:
type:script
message:stopping WAN Guard
description:Stop WAN Guard

[restart]
command:/usr/local/etc/rc.d/wanguard restart
parameters:
type:script
message:restarting WAN Guard
description:Restart WAN Guard

[status]
command:/usr/local/etc/rc.d/wanguard onestatus
parameters:
type:script_output
message:request WAN Guard status
errors:no

[reload]
command:/usr/local/etc/rc.d/wanguard reload
parameters:
type:script
message:asking WAN Guard to observe its interfaces

[state]
command:/usr/local/bin/python3 -B /usr/local/opnsense/scripts/wanguard/wanguard.py state
parameters:
type:script_output
message:request WAN Guard interface state

[retry]
command:/usr/local/bin/python3 -B /usr/local/opnsense/scripts/wanguard/wanguard.py retry
parameters:%s
type:script_output
message:queue a WAN Guard retry for %s
