###################################################################
# Local syslog-ng configuration filter definition [wanguard].
###################################################################
filter f_local_wanguard {
    program("wanguard");
};
