#!/bin/sh
[ -n "${PKG_UPGRADE+x}" ] && exit 0
service configd restart >/dev/null 2>&1 || true
/usr/local/opnsense/scripts/firmware/register.php remove os-unboundcustom >/dev/null 2>&1 || true
rm -f /var/lib/php/tmp/opnsense_menu_cache.xml
exit 0
