[start]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/ttyd/manage.py start
parameters:
type:script_output
message:ttyd start

[stop]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/ttyd/manage.py stop
parameters:
type:script_output
message:ttyd stop

[restart]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/ttyd/manage.py restart
parameters:
type:script_output
message:ttyd restart

[status]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/ttyd/manage.py status
parameters:
type:script_output
message:ttyd status
