[start]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frps start
parameters:
type:script_output
message:frps start

[stop]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frps stop
parameters:
type:script_output
message:frps stop

[restart]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frps restart
parameters:
type:script_output
message:frps restart

[status]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frps status
parameters:
type:script_output
message:frps status

[settings]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frps settings
parameters:
type:script_output
message:frps settings

[set-settings]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frps set-settings
parameters:%s
type:script_output
message:frps set-settings

[verify]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frps verify
parameters:%s
type:script_output
message:frps verify

[log]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frps log
parameters:
type:script_output
message:frps log
