[start]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frpc start
parameters:
type:script_output
message:frpc start

[stop]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frpc stop
parameters:
type:script_output
message:frpc stop

[restart]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frpc restart
parameters:
type:script_output
message:frpc restart

[status]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frpc status
parameters:
type:script_output
message:frpc status

[settings]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frpc settings
parameters:
type:script_output
message:frpc settings

[set-settings]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frpc set-settings
parameters:%s
type:script_output
message:frpc set-settings

[verify]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frpc verify
parameters:%s
type:script_output
message:frpc verify

[log]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/frp/manage.py --json frpc log
parameters:
type:script_output
message:frpc log
