[start]
command:sh /usr/local/etc/rc.d/os-ddns-go onestart
parameters:
type:script
message:starting ddns-go

[stop]
command:sh /usr/local/etc/rc.d/os-ddns-go onestop
parameters:
type:script
message:stopping ddns-go

[restart]
command:sh /usr/local/etc/rc.d/os-ddns-go onerestart
parameters:
type:script
message:restarting ddns-go
description:Restart DDNS-Go service

[status]
command:sh /usr/local/etc/rc.d/os-ddns-go onestatus
parameters:
type:script_output
message:request ddns-go status

[get]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/ddnsgo/settings.py get
parameters:
type:script_output
message:get ddnsgo settings

[set]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/ddnsgo/settings.py set
parameters:%s
type:script_output
message:set ddnsgo settings

[log]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/ddnsgo/settings.py log
parameters:
type:script_output
message:request redacted DDNS-Go log
