#!/bin/sh
set -eu

# Preserve settings before pkg removes the outgoing package's owned files.
upgrade_state=/var/db/os-staticarp
upgrade_rc=/etc/rc.conf.d/staticarp
if [ -f "$upgrade_rc" ]; then
    install -d -m 0700 "$upgrade_state"
    cp -p "$upgrade_rc" "$upgrade_state/rc.conf.upgrade"
fi
if [ -d /usr/local/etc/staticarp ]; then
    install -d -m 0700 "$upgrade_state"
    rm -rf "$upgrade_state/state.upgrade.new"
    cp -pR /usr/local/etc/staticarp "$upgrade_state/state.upgrade.new"
    rm -rf "$upgrade_state/state.upgrade"
    mv "$upgrade_state/state.upgrade.new" "$upgrade_state/state.upgrade"
fi
