<style>
.langtool-output {max-height: 350px; max-width: 100%; overflow: auto; white-space: pre-wrap;}
.langtool-actions {padding: 12px 15px;}
</style>
<form id="frmLangTool">
<div class="alert alert-danger hidden" id="langtool-error" role="alert"></div>
<div class="content-box"><table class="table table-condensed table-striped"><thead><tr><th><span data-lang-label="Chinese localization package">{{ lang._('Chinese localization package') }}</span></th><th class="text-right"><small><span data-lang-label="full help">{{ lang._('full help') }}</span> </small><a href="#"><i class="fa fa-toggle-off text-danger" id="show_all_help_langtool"></i></a></th></tr></thead><tbody>
<tr><th><a href="#" class="showhelp" id="help_for_langtool_version"><i class="fa fa-info-circle"></i></a> <span data-lang-label="Current OPNsense version">{{ lang._('Current OPNsense version') }}</span></th><td><span id="langtool-version">-</span><div class="hidden" data-for="help_for_langtool_version" data-lang-label="Installed OPNsense version. Check the localization package notes before updating after a firmware upgrade.">{{ lang._('Installed OPNsense version. Check the localization package notes before updating after a firmware upgrade.') }}</div></td></tr>
<tr><th><a href="#" class="showhelp" id="help_for_langtool_language"><i class="fa fa-info-circle"></i></a> <span data-lang-label="Current language">{{ lang._('Current language') }}</span></th><td><span id="langtool-language">-</span><div class="hidden" data-for="help_for_langtool_language" data-lang-label="The language selected in your WebGUI settings. Installing localization files keeps this language selection.">{{ lang._('The language selected in your WebGUI settings. Installing localization files keeps this language selection.') }}</div></td></tr>
<tr><th><a href="#" class="showhelp" id="help_for_langtool_source"><i class="fa fa-info-circle"></i></a> <span data-lang-label="Download source">{{ lang._('Download source') }}</span></th><td><span id="langtool-source">-</span><div class="hidden" data-for="help_for_langtool_source" data-lang-label="Downloads the localization ZIP over HTTPS from pfchina.org. The download source is fixed for this tool.">{{ lang._('Downloads the localization ZIP over HTTPS from pfchina.org. The download source is fixed for this tool.') }}</div></td></tr>
</tbody></table><div class="langtool-actions"><p class="text-muted" data-lang-label="The package is downloaded from the trusted pfchina.org source and installed under /usr/local.">{{ lang._('The package is downloaded from the trusted pfchina.org source and installed under /usr/local.') }}</p>
<p><a href="#" class="showhelp" id="help_for_langtool_update"><i class="fa fa-info-circle"></i></a> <span data-lang-label="Update localization">{{ lang._('Update localization') }}</span></p>
<div class="hidden" data-for="help_for_langtool_update" data-lang-label="Update downloads and installs the shared localization package in the background. It updates translation files without changing the selected language. Wait for completion, read the package notes, and refresh after the WebGUI reloads.">{{ lang._('Update downloads and installs the shared localization package in the background. It updates translation files without changing the selected language. Wait for completion, read the package notes, and refresh after the WebGUI reloads.') }}</div>
<button type="button" class="btn btn-primary" id="langtool-update"><i class="fa fa-download fa-fw"></i> <span data-lang-label="Update localization">{{ lang._('Update localization') }}</span></button></div></div>
<div class="content-box"><table class="table table-condensed"><thead><tr><th><a href="#" class="showhelp" id="help_for_langtool_status"><i class="fa fa-info-circle"></i></a> <span data-lang-label="Status">{{ lang._('Status') }}</span></th></tr></thead><tbody><tr><td><div class="hidden" data-for="help_for_langtool_status" data-lang-label="Shows the latest update progress and result. Only one update runs at a time; the update button becomes available again when it finishes.">{{ lang._('Shows the latest update progress and result. Only one update runs at a time; the update button becomes available again when it finishes.') }}</div><pre class="langtool-output" id="langtool-log"></pre><p class="text-muted" data-lang-label="Refresh the page after the WebGUI reloads.">{{ lang._('Refresh the page after the WebGUI reloads.') }}</p></td></tr></tbody></table></div>
<div class="content-box hidden" id="langtool-readme-box"><table class="table table-condensed"><thead><tr><th data-lang-label="Readme">{{ lang._('Readme') }}</th></tr></thead><tbody><tr><td><pre class="langtool-output" id="langtool-readme"></pre></td></tr></tbody></table></div>
</form>
<script>
$(function () {
    var messages = {"Services": {"zh_cn": "服务", "zh_tw": "服務"}, "Localization Tool": {"zh_cn": "汉化工具", "zh_tw": "漢化工具"}, "Chinese localization package": {"zh_cn": "中文语言包", "zh_tw": "中文語言包"}, "Current OPNsense version": {"zh_cn": "当前 OPNsense 版本", "zh_tw": "目前 OPNsense 版本"}, "Current language": {"zh_cn": "当前语言", "zh_tw": "目前語言"}, "Download source": {"zh_cn": "下载源", "zh_tw": "下載來源"}, "Update localization": {"zh_cn": "更新汉化", "zh_tw": "更新漢化"}, "Updating...": {"zh_cn": "正在更新...", "zh_tw": "正在更新..."}, "Status": {"zh_cn": "执行状态", "zh_tw": "執行狀態"}, "Readme": {"zh_cn": "更新说明", "zh_tw": "更新說明"}, "Unknown": {"zh_cn": "未知", "zh_tw": "未知"}, "Refresh the page after the WebGUI reloads.": {"zh_cn": "WebGUI 重新加载后请刷新页面。", "zh_tw": "WebGUI 重新載入後請重新整理頁面。"}, "The package is downloaded from the trusted pfchina.org source and installed under /usr/local.": {"zh_cn": "语言包会从受信任的 pfchina.org 下载源获取，并安装到 /usr/local。", "zh_tw": "語言包會從受信任的 pfchina.org 下載來源取得，並安裝到 /usr/local。"}, "Invalid form token, please refresh and try again.": {"zh_cn": "表单令牌无效，请刷新页面后重试。", "zh_tw": "表單權杖無效，請重新整理頁面後再試。"}, "Invalid download URL.": {"zh_cn": "下载链接无效。", "zh_tw": "下載連結無效。"}, "Download URL must use HTTPS.": {"zh_cn": "下载链接必须使用 HTTPS。", "zh_tw": "下載連結必須使用 HTTPS。"}, "Download host is not trusted": {"zh_cn": "下载域名不在信任列表中", "zh_tw": "下載網域不在信任清單中"}, "Unable to create temporary directory.": {"zh_cn": "无法创建临时目录。", "zh_tw": "無法建立暫存目錄。"}, "Downloading package...": {"zh_cn": "正在下载语言包...", "zh_tw": "正在下載語言包..."}, "Download completed.": {"zh_cn": "下载完成。", "zh_tw": "下載完成。"}, "Download failed.": {"zh_cn": "下载失败。", "zh_tw": "下載失敗。"}, "Checksum verification failed.": {"zh_cn": "压缩包校验失败。", "zh_tw": "壓縮包校驗失敗。"}, "Reading archive file list...": {"zh_cn": "正在读取压缩包文件列表...", "zh_tw": "正在讀取壓縮包檔案清單..."}, "Archive is empty.": {"zh_cn": "压缩包为空。", "zh_tw": "壓縮包為空。"}, "Archive contains unsafe path": {"zh_cn": "压缩包包含不安全路径", "zh_tw": "壓縮包包含不安全路徑"}, "Archive contains unsupported path": {"zh_cn": "压缩包包含未允许的安装路径", "zh_tw": "壓縮包包含未允許的安裝路徑"}, "Extracting package...": {"zh_cn": "正在解压语言包...", "zh_tw": "正在解壓語言包..."}, "Extraction failed.": {"zh_cn": "解压失败。", "zh_tw": "解壓失敗。"}, "Installing localization files...": {"zh_cn": "正在安装汉化文件...", "zh_tw": "正在安裝漢化檔案..."}, "Installation failed.": {"zh_cn": "汉化文件安装失败。", "zh_tw": "漢化檔案安裝失敗。"}, "Localization completed.": {"zh_cn": "汉化完成。", "zh_tw": "漢化完成。"}, "No readme.md found in the package.": {"zh_cn": "语言包中未找到 readme.md。", "zh_tw": "語言包中未找到 readme.md。"}, "Cleaning temporary files...": {"zh_cn": "正在清理临时文件...", "zh_tw": "正在清理暫存檔案..."}, "Reloading WebGUI...": {"zh_cn": "正在重新加载 WebGUI...", "zh_tw": "正在重新載入 WebGUI..."}}, family = '', waiting = false;
    $.extend(messages, {
        'full help': {'zh_cn': '完整帮助', 'zh_tw': '完整說明'},
        'Installed OPNsense version. Check the localization package notes before updating after a firmware upgrade.': {'zh_cn': '显示已安装的 OPNsense 版本。固件升级后更新汉化前，请先查看语言包说明。', 'zh_tw': '顯示已安裝的 OPNsense 版本。韌體升級後更新漢化前，請先查看語言包說明。'},
        'The language selected in your WebGUI settings. Installing localization files keeps this language selection.': {'zh_cn': '显示 WebGUI 设置中选择的语言。安装汉化文件会保留当前语言选择。', 'zh_tw': '顯示 WebGUI 設定中選擇的語言。安裝漢化檔案會保留目前語言選擇。'},
        'Downloads the localization ZIP over HTTPS from pfchina.org. The download source is fixed for this tool.': {'zh_cn': '通过 HTTPS 从 pfchina.org 下载语言压缩包。本工具使用固定下载源。', 'zh_tw': '透過 HTTPS 從 pfchina.org 下載語言壓縮包。本工具使用固定下載來源。'},
        'Update downloads and installs the shared localization package in the background. It updates translation files without changing the selected language. Wait for completion, read the package notes, and refresh after the WebGUI reloads.': {'zh_cn': '更新会在后台下载并安装公共语言包，更新翻译文件并保留当前语言选择。请等待完成，查看语言包说明，并在 WebGUI 重新加载后刷新页面。', 'zh_tw': '更新會在背景下載並安裝共用語言包，更新翻譯檔案並保留目前語言選擇。請等待完成，查看語言包說明，並在 WebGUI 重新載入後重新整理頁面。'},
        'Shows the latest update progress and result. Only one update runs at a time; the update button becomes available again when it finishes.': {'zh_cn': '显示最近一次更新的进度和结果。一次只运行一个更新任务，完成后更新按钮会恢复可用。', 'zh_tw': '顯示最近一次更新的進度和結果。一次只執行一個更新工作，完成後更新按鈕會恢復可用。'}
    });
    function t(value) {return (messages[value] || {})[family] || value;}
    function error(value) {$('#langtool-error').toggleClass('hidden', !value).text(htmlDecode(value || ''));}
    function refresh() {
        ajaxGet('/api/langtool/service/status', {}, function (data) {
            data = data || {}; var language = htmlDecode(data.language || '').toLowerCase().replace('-', '_');
            family = /zh_(tw|hk|mo)|hant/.test(language) ? 'zh_tw' : (/^zh($|_(cn|sg))|hans/.test(language) ? 'zh_cn' : '');
            $('[data-lang-label]').each(function () {$(this).text(t($(this).attr('data-lang-label')));});
            ['version','language','source'].forEach(function (key) {$('#langtool-' + key).text(htmlDecode(data[key] || '-'));});
            $('#langtool-log').text(htmlDecode(data.log || '')); $('#langtool-readme').text(htmlDecode(data.readme || '')); $('#langtool-readme-box').toggleClass('hidden', !data.readme);
            $('#langtool-update').prop('disabled', !!data.running || waiting).find('i').toggleClass('fa-download', !data.running).toggleClass('fa-spinner fa-spin', !!data.running);
            $('#langtool-update span').text(t(data.running ? 'Updating...' : 'Update localization'));
            error(data.error || '');
        });
    }
    $('#langtool-update').click(function () {
        waiting = true; $(this).prop('disabled', true); error('');
        ajaxCall('/api/langtool/service/update', {}, function (data) {waiting = false; if ((data || {}).status !== 'ok') {error((data || {}).error || '{{ lang._("Unable to start localization update.") }}');} refresh();});
    });
    refresh(); window.setInterval(refresh, 2000);
});
</script>
