[start]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php start
parameters:
type:script_output

[stop]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php stop
parameters:
type:script_output

[restart]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php restart
parameters:
type:script_output
description:Restart sing-box service

[status]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php status
parameters:
type:script_output

[get-settings]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php get-settings
parameters:
type:script_output

[set-settings]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php set-settings
parameters:%s
type:script_output

[save-config]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php save-config
parameters:%s
type:script_output

[sub-update]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php sub-update
parameters:
type:script_output
description:Renew sing-box Subscription

[update-status]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php update-status
parameters:
type:script_output

[log]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php log
parameters:
type:script_output

[sub-log]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php sub-log
parameters:
type:script_output

[clear-log]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php clear-log
parameters:
type:script_output

[clear-sub-log]
command:/usr/local/bin/php /usr/local/opnsense/scripts/singbox/singbox.php clear-sub-log
parameters:
type:script_output
