[status]
command:/usr/local/bin/php /usr/local/opnsense/scripts/langtool/manage.php status
parameters:
type:script_output
message:request localization status

[update]
command:/usr/local/bin/php /usr/local/opnsense/scripts/langtool/manage.php update
parameters:
type:script_output
message:update localization
