"""Exercise DNS changes, loaded-config receipts, and failure recovery in isolation."""
import errno
import importlib.util
import json
import os
from pathlib import Path
import sys
import tempfile
from types import SimpleNamespace
import unittest
from unittest.mock import patch

PACKAGE = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PACKAGE.parent / 'common'))
spec = importlib.util.spec_from_file_location('unboundcustom_apply', PACKAGE / 'src/opnsense/scripts/OPNsense/Unboundcustom/apply.py')
apply = importlib.util.module_from_spec(spec)
spec.loader.exec_module(apply)
REAL_RESOLVER = apply.resolver
REAL_PIDFILE_IDENTITY = apply.pidfile_identity


class ApplyTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix='unboundcustom-transaction-')
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name)
        self.fragment = self.root / 'generated.conf'
        self.runtime = self.root / 'etc/custom-options.conf'
        self.runtime.parent.mkdir()
        self.state = self.root / 'state'
        self.state.mkdir()
        (self.root / 'unbound.conf').write_text('server:\ninclude: ' + str(self.root / 'etc/*.conf') + '\n')
        self.old = b'# Generated by os-unboundcustom.\nserver:\n verbosity: 1\n'
        self.generated = b'# Generated by os-unboundcustom.\nserver:\n verbosity: 3\n'
        self.fragment.write_bytes(self.old)
        self.runtime.write_bytes(self.old)
        self.fragment.chmod(0o600)
        self.runtime.chmod(0o640)
        self.running = {'pid': 10, 'birth': '100:1234'}
        self.events = []
        self.validation_states = []
        self.failure = ''
        self.launches = 0
        self.tick = 0
        mappings = {'FRAGMENT': self.fragment, 'RUNTIME': self.runtime, 'ROOT': self.root, 'STATE': self.state}
        self.addCleanup(patch.stopall)
        patch.multiple(apply, **mappings).start()
        patch.object(apply, 'resolver', side_effect=lambda: self.running).start()
        patch.object(apply, 'process', side_effect=self.process).start()
        patch.object(apply, 'pidfile_identity', side_effect=lambda: self.process(self.running['pid']) if self.running else None).start()
        patch.object(apply.os, 'kill', side_effect=self.kill).start()
        patch.object(apply.subprocess, 'Popen', side_effect=self.launch).start()
        patch.object(apply.time, 'sleep', return_value=None).start()
        patch.object(apply.time, 'monotonic', side_effect=self.clock).start()
        patch.object(apply, 'run', side_effect=self.command).start()
        patch.object(apply.pwd, 'getpwnam', return_value=SimpleNamespace(pw_uid=os.getuid(), pw_gid=os.getgid())).start()
        # Preserve owner semantics without requiring local root for fixtures.
        self.actual_fchown = os.fchown
        patch.object(apply.os, 'fchown', side_effect=lambda fd, uid, gid: None).start()

    def command(self, command, timeout=90, cwd=None):
        self.events.append(command)
        if command[:2] == [apply.TEMPLATE_CTL, '-r']:
            target = apply.rooted(Path(command[2]), self.fragment)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(self.generated)
            target.chmod(0o600)
            if self.failure == 'template':
                raise RuntimeError('isolated template failure')
            return b'templates...done\n'
        elif command[0] == apply.CHECKCONF:
            candidate = Path(command[1]).parent / 'etc' / self.runtime.name
            if candidate.exists():
                self.validation_states.append((self.fragment.read_bytes() if self.fragment.exists() else None,
                                               self.runtime.read_bytes() if self.runtime.exists() else None,
                                               candidate.read_bytes()))
            if self.failure == 'validation' and candidate.exists():
                raise RuntimeError('isolated syntax failure')
            if self.failure == 'admin-stop':
                self.running = None
            elif self.failure == 'admin-change':
                self.running = {'pid': 99, 'birth': '999:1234'}
        return b''

    def clock(self):
        self.tick += 0.1
        return self.tick

    def process(self, pid):
        if self.running and self.running['pid'] == pid:
            return {**self.running, 'executable': apply.UNBOUND, 'uid': os.getuid(), 'stopped': False,
                    'argv': [apply.UNBOUND, '-d', '-c', str(self.root / 'unbound.conf')]}
        return None

    def kill(self, pid, signum):
        self.events.append(['signal', pid, signum])
        if self.failure == 'restart-alive':
            raise OSError('isolated signal failure before stop')
        self.assertEqual(pid, self.running['pid'])
        self.running = None

    def launch(self, command, **kwargs):
        self.events.append(command)
        self.launches += 1
        pid = 10 + self.launches
        failed = self.failure == 'recover' or (self.failure == 'restart' and self.launches == 1)
        if failed:
            self.running = None
        else:
            self.running = {'pid': pid, 'birth': '%d:1234' % (200 + self.launches)}
        return SimpleNamespace(pid=pid, poll=lambda: 1 if failed else (None if self.running and self.running['pid'] == pid else 0), wait=lambda timeout: 0)

    def attempt(self, failure='', remove=False):
        self.failure = failure
        try:
            return apply.transaction(remove=remove)
        except apply.ApplyError as error:
            return {'status': 'failed', 'code': error.code, 'detail': str(error)}

    def restarts(self):
        return sum(event[:1] == ['signal'] for event in self.events)

    def assert_restored(self):
        self.assertEqual(self.fragment.read_bytes(), self.old)
        self.assertEqual(self.runtime.read_bytes(), self.old)
        self.assertEqual(self.fragment.stat().st_mode & 0o777, 0o600)
        self.assertEqual(self.runtime.stat().st_mode & 0o777, 0o640)

    def test_valid_change_restarts_once_and_repeated_apply_keeps_same_process(self):
        self.assertEqual(self.attempt()['status'], 'ok')
        self.assertEqual(self.restarts(), 1)
        process = self.running.copy()
        self.assertFalse(self.attempt()['restarted'])
        self.assertEqual(self.running, process)
        self.assertEqual(self.restarts(), 1)
        self.assertEqual((self.state / 'applied.json').stat().st_mode & 0o777, 0o600)

    def test_template_and_candidate_trees_stay_below_private_state(self):
        self.assertEqual(self.attempt()['status'], 'ok')
        template_root = next(Path(command[2]) for command in self.events
                             if command[:2] == [apply.TEMPLATE_CTL, '-r'])
        candidate_main = next(Path(command[1]) for command in self.events
                              if command[0] == apply.CHECKCONF and Path(command[1]).is_absolute())
        self.assertEqual(template_root.parent, self.state)
        self.assertEqual(candidate_main.parent.parent, self.state)
        self.assertEqual(list(self.state.glob('.template-*')), [])
        self.assertEqual(list(self.state.glob('.check-*')), [])

    def test_missing_template_target_fails_before_live_mutation(self):
        with patch.object(apply, 'run', return_value=b'templates...done\n'):
            report = self.attempt()
        self.assertEqual(report['code'], 'template_failed')
        self.assert_restored()
        self.assertEqual(self.restarts(), 0)

    def test_template_renderer_failure_text_is_not_accepted_with_a_zero_exit(self):
        original = self.command
        def failed(command, timeout=90, cwd=None):
            if command[:2] == [apply.TEMPLATE_CTL, '-r']:
                target = apply.rooted(Path(command[2]), self.fragment)
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(self.generated)
                return b'templates...failed\n'
            return original(command, timeout=timeout, cwd=cwd)
        with patch.object(apply, 'run', side_effect=failed):
            report = self.attempt()
        self.assertEqual(report['code'], 'template_failed')
        self.assert_restored()
        self.assertEqual(self.restarts(), 0)

    def test_disabled_first_install_and_repeated_apply_never_restart(self):
        self.fragment.unlink()
        self.runtime.unlink()
        self.generated = b'\n'
        self.assertFalse(self.attempt()['restarted'])
        self.assertFalse(self.attempt()['restarted'])
        self.assertEqual(self.restarts(), 0)

    def test_native_resolver_intentionally_stopped_is_not_started(self):
        self.running = None
        self.assertFalse(self.attempt()['restarted'])
        self.assertFalse(any(command[0] == apply.UNBOUND for command in self.events))
        self.assertIsNone(self.running)

    def test_malformed_pidfile_aborts_before_mutation_or_ownership_claim(self):
        pidfile = self.root / 'unbound.pid'
        for content in (b'not-a-pid\n', b'\xff', b' 10\n', b'10\n\n', b'2147483648\n'):
            with self.subTest(content=content):
                pidfile.write_bytes(content)
                with (patch.object(apply, 'PIDFILE', pidfile), patch.object(apply, 'resolver', REAL_RESOLVER),
                      patch.object(apply, 'pidfile_identity', REAL_PIDFILE_IDENTITY)):
                    with self.assertRaisesRegex(RuntimeError, 'PID file is malformed'):
                        apply.transaction()
                self.assert_restored()
                self.assertEqual(self.events, [])
                self.assertFalse((self.state / 'applied.json').exists())

    def test_identity_lookup_error_aborts_before_mutation_or_ownership_claim(self):
        pidfile = self.root / 'unbound.pid'
        pidfile.write_text('10\n')
        for number in (errno.EPERM, errno.EIO):
            error = OSError(number, 'injected process metadata failure')
            with (self.subTest(number=number), patch.object(apply, 'PIDFILE', pidfile),
                  patch.object(apply, 'resolver', REAL_RESOLVER),
                  patch.object(apply, 'pidfile_identity', REAL_PIDFILE_IDENTITY),
                  patch.object(apply, 'process', side_effect=error)):
                with self.assertRaises(OSError) as raised:
                    apply.transaction()
            self.assertEqual(raised.exception.errno, number)
            self.assert_restored()
            self.assertEqual(self.events, [])
            self.assertFalse((self.state / 'applied.json').exists())

    def test_live_foreign_pid_slot_aborts_before_mutation_or_ownership_claim(self):
        pidfile = self.root / 'unbound.pid'
        pidfile.write_text('10\n')
        foreign = {**self.process(10), 'executable': '/usr/local/sbin/foreign-unbound'}
        with (patch.object(apply, 'PIDFILE', pidfile), patch.object(apply, 'resolver', REAL_RESOLVER),
              patch.object(apply, 'pidfile_identity', REAL_PIDFILE_IDENTITY),
              patch.object(apply, 'process', return_value=foreign)):
            with self.assertRaisesRegex(RuntimeError, 'does not reference the expected Unbound process'):
                apply.transaction()
        self.assert_restored()
        self.assertEqual(self.events, [])
        self.assertFalse((self.state / 'applied.json').exists())

    def test_pending_external_include_change_is_not_hidden_by_owned_fragment_noop(self):
        self.attempt()
        (self.root / 'etc/another-plugin.conf').write_text('server:\nverbosity: 2\n')
        self.assertTrue(self.attempt()['restarted'])
        self.assertEqual(self.restarts(), 2)

    def test_repairing_only_the_template_source_does_not_restart_dns(self):
        self.attempt()
        self.events.clear()
        self.fragment.write_bytes(self.old)
        process = self.running.copy()
        self.assertFalse(self.attempt()['restarted'])
        self.assertEqual(self.fragment.read_bytes(), self.generated)
        self.assertEqual(self.running, process)
        self.assertEqual(self.restarts(), 0)

    def test_changed_main_listener_and_unknown_include_force_conservative_restart(self):
        self.attempt()
        main = self.root / 'unbound.conf'
        main.write_text(main.read_text() + 'interface: 127.0.0.2\n')
        self.assertTrue(self.attempt()['restarted'])
        main.write_text(main.read_text() + 'include: /external/untracked.conf\n')
        self.assertIsNone(apply.closure())
        self.assertTrue(self.attempt()['restarted'])

    def test_new_resolver_process_invalidates_loaded_config_receipt(self):
        self.attempt()
        self.running = {'pid': 11, 'birth': '999:1234'}
        self.assertTrue(self.attempt()['restarted'])

    def test_template_or_validation_failure_restores_exact_files_without_restart(self):
        for failure, code in [('template', 'template_failed'), ('validation', 'validation_failed')]:
            with self.subTest(failure=failure):
                report = self.attempt(failure)
                self.assertEqual(report['code'], code)
                self.assert_restored()
                self.assertEqual(self.restarts(), 0)
                if failure == 'validation':
                    self.assertEqual(self.validation_states, [(self.old, self.old, self.generated)])

    def test_failed_restart_restores_files_then_starts_restored_config_without_rerendering(self):
        report = self.attempt('restart')
        self.assertEqual(report['code'], 'restart_failed')
        self.assert_restored()
        self.assertIsNotNone(self.running)
        self.assertEqual(self.restarts(), 1)
        self.assertEqual(sum(command[0] == apply.UNBOUND for command in self.events), 2)
        self.assertEqual(sum(command[:2] == [apply.TEMPLATE_CTL, '-r'] for command in self.events), 1)

    def test_failed_restart_that_kept_original_process_does_not_interrupt_it(self):
        original = self.running.copy()
        self.assertEqual(self.attempt('restart-alive')['code'], 'restart_failed')
        self.assertEqual(self.running, original)
        self.assert_restored()
        self.assertFalse(any(command[0] == apply.UNBOUND for command in self.events))

    def test_failure_after_owned_process_started_stops_only_our_child_and_restores_config(self):
        original = apply.atomic
        failed = [False]
        def write(path, *args, **kwargs):
            if path == self.state / 'applied.json' and not failed[0]:
                failed[0] = True
                raise OSError('isolated journal commit failure')
            return original(path, *args, **kwargs)
        with patch.object(apply, 'atomic', side_effect=write):
            self.assertEqual(self.attempt()['code'], 'apply_failed')
        self.assert_restored()
        self.assertEqual([event[1] for event in self.events if event[0] == 'signal'], [10, 11])
        self.assertEqual(self.running['pid'], 12)

    def test_failed_recovery_reports_failure_instead_of_claiming_resolver_restored(self):
        report = self.attempt('recover')
        self.assertEqual(report['code'], 'recovery_failed')
        self.assertIn('exited during startup', report['detail'])
        self.assertIsNone(self.running)
        self.assert_restored()

    def test_recovery_rereads_pid_slot_after_original_exits_at_confirmation_boundary(self):
        original = {'pid': 10, 'birth': '100:1234'}
        slot = [original]
        launches = []
        attempt = {'stopped': False, 'term_sent': True}

        def confirm_exit():
            slot[0] = None
            return None

        def launch(restored):
            launches.append(restored)

        with (patch.object(apply, 'resolver', side_effect=confirm_exit),
              patch.object(apply, 'pidfile_identity', side_effect=lambda: slot[0]),
              patch.object(apply, 'process', return_value=None),
              patch.object(apply, 'validate', return_value=None),
              patch.object(apply, 'start_owned', side_effect=launch)):
            detail = apply.recover(original, attempt)
        self.assertTrue(attempt['stopped'])
        self.assertEqual(launches, [{'stopped': True}])
        self.assertIn('restored and started', detail)

    def test_true_remove_restarts_only_for_removed_owned_active_content(self):
        self.attempt()
        self.events.clear()
        self.assertTrue(self.attempt(remove=True)['restarted'])
        self.assertFalse(self.fragment.exists())
        self.assertFalse(self.runtime.exists())
        self.assertEqual(self.restarts(), 1)

    def test_remove_preserves_foreign_same_named_files_without_resolver_restart(self):
        self.fragment.write_bytes(b'server:\nverbosity: 5\n')
        self.runtime.write_bytes(b'server:\nverbosity: 6\n')
        report = self.attempt(remove=True)
        self.assertFalse(report['restarted'])
        self.assertEqual(self.runtime.read_bytes(), b'server:\nverbosity: 6\n')
        self.assertEqual(self.events, [])

    def test_remove_preserves_later_administrator_edit_even_with_generated_marker(self):
        self.attempt()
        edited = self.generated + b'# administrator edit\n'
        self.fragment.write_bytes(edited)
        self.runtime.write_bytes(edited)
        self.events.clear()
        self.assertFalse(self.attempt(remove=True)['restarted'])
        self.assertEqual(self.fragment.read_bytes(), edited)
        self.assertEqual(self.runtime.read_bytes(), edited)
        self.assertEqual(self.events, [])
        receipt = json.loads((self.state / 'applied.json').read_text())
        self.assertEqual(receipt['owned'], {str(self.fragment): None, str(self.runtime): None})
        self.assertFalse(self.attempt(remove=True)['restarted'])
        self.assertEqual(self.fragment.read_bytes(), edited)
        self.assertEqual(self.runtime.read_bytes(), edited)

    def test_closure_rejects_symlink_and_bounds_untracked_globs(self):
        (self.root / 'etc/untracked.conf').symlink_to(self.fragment)
        self.assertIsNone(apply.closure())
        (self.root / 'etc/untracked.conf').unlink()
        (self.root / 'unbound.conf').write_text('include: ' + str(self.root / 'etc/special*.conf') + '\n')
        self.assertIsNone(apply.closure())

    def test_candidate_rejects_symlinked_native_include_before_live_mutation(self):
        outside = self.root / 'outside.conf'
        outside.write_text('server:\nverbosity: 5\n')
        (self.root / 'etc/symlink.conf').symlink_to(outside)
        report = self.attempt()
        self.assertEqual(report['code'], 'validation_failed')
        self.assert_restored()
        self.assertEqual(self.restarts(), 0)

    def test_candidate_rejects_invalid_main_encoding_and_ambiguous_native_glob(self):
        main = self.root / 'unbound.conf'
        variants = [b'\xff',
                    ('include: %s\ninclude: %s\n' %
                     (self.root / 'etc/*.conf', self.root / 'etc/*.conf')).encode()]
        for data in variants:
            with self.subTest(data=data):
                main.write_bytes(data)
                self.events.clear()
                report = self.attempt()
                self.assertEqual(report['code'], 'validation_failed')
                self.assert_restored()
                self.assertEqual(self.restarts(), 0)

    def test_unsafe_receipt_permissions_and_symlink_are_never_trusted(self):
        self.attempt()
        receipt = self.state / 'applied.json'
        current_fragment = self.fragment.read_bytes()
        current_runtime = self.runtime.read_bytes()
        receipt.chmod(0o640)
        self.events.clear()
        self.assertEqual(self.attempt()['code'], 'state_failed')
        self.assertEqual(self.fragment.read_bytes(), current_fragment)
        self.assertEqual(self.runtime.read_bytes(), current_runtime)
        self.assertEqual(self.events, [])
        receipt.unlink()
        target = self.state / 'foreign-receipt'
        target.write_text('{}')
        receipt.symlink_to(target)
        self.assertEqual(self.attempt()['code'], 'state_failed')
        self.assertTrue(receipt.is_symlink())
        self.assertEqual(target.read_text(), '{}')
        self.assertEqual(self.events, [])

    def test_corrupt_or_unsupported_receipts_preserve_all_files_before_any_command(self):
        valid = {'owned': {str(self.fragment): apply.snapshot(self.fragment), str(self.runtime): apply.snapshot(self.runtime)},
                 'closure': None, 'resolver': None}
        cases = ['{broken', '[]', 'null', '42', '"text"', '{}', json.dumps({**valid, 'owned': []}),
                 json.dumps({**valid, 'owned': {}}), json.dumps({**valid, 'resolver': {'pid': True, 'birth': '1:1'}}),
                 json.dumps({**valid, 'closure': 'bad'})]
        for bad in ({'data': '@bad', 'mode': 0o600, 'uid': 0, 'gid': 0},
                    {'data': '', 'mode': True, 'uid': 0, 'gid': 0}, []):
            cases.append(json.dumps({**valid, 'owned': {str(self.fragment): bad, str(self.runtime): None}}))
        for case in cases:
            for remove in [False, True]:
                with self.subTest(case=case, remove=remove):
                    (self.state / 'applied.json').write_text(case)
                    self.events.clear()
                    self.assertEqual(self.attempt(remove=remove)['code'], 'state_failed')
                    self.assert_restored()
                    self.assertEqual(self.events, [])
                    self.assertEqual(self.running['pid'], 10)

    def test_corrupt_receipt_never_downgrades_edited_marker_to_legacy_ownership(self):
        self.attempt()
        edited = self.generated + b'# administrator edit retained\n'
        self.fragment.write_bytes(edited)
        self.runtime.write_bytes(edited)
        (self.state / 'applied.json').write_text('{broken')
        self.events.clear()
        self.assertEqual(self.attempt(remove=True)['code'], 'state_failed')
        self.assertEqual(self.fragment.read_bytes(), edited)
        self.assertEqual(self.runtime.read_bytes(), edited)
        self.assertEqual(self.events, [])

    def test_failed_transaction_retains_prior_exact_ownership_for_later_remove(self):
        self.attempt()
        receipt = self.state / 'applied.json'
        previous = receipt.read_bytes()
        self.generated = self.generated.replace(b'verbosity: 3', b'verbosity: 4')
        self.assertEqual(self.attempt('validation')['code'], 'validation_failed')
        self.assertEqual(receipt.read_bytes(), previous)
        edited = self.runtime.read_bytes() + b'# retained administrator edit\n'
        self.fragment.write_bytes(edited)
        self.runtime.write_bytes(edited)
        self.failure = ''
        self.assertFalse(self.attempt(remove=True)['restarted'])
        self.assertEqual(self.runtime.read_bytes(), edited)

    def test_admin_stop_or_replacement_before_signal_does_not_start_or_kill(self):
        for failure in ['admin-stop', 'admin-change']:
            with self.subTest(failure=failure):
                self.running = {'pid': 10, 'birth': '100:1234'}
                self.events.clear()
                self.assertEqual(self.attempt(failure)['code'], 'restart_failed')
                self.assert_restored()
                self.assertFalse(any(event[0] in ['signal', apply.UNBOUND] for event in self.events))
                self.assertEqual(self.running, None if failure == 'admin-stop' else {'pid': 99, 'birth': '999:1234'})

    def test_direct_restart_and_failed_start_preserve_native_main_and_other_include(self):
        native = self.root / 'etc/native.conf'
        native.write_bytes(b'server:\nprivate-domain: "native.invalid"\n')
        main = (self.root / 'unbound.conf').read_bytes()
        native_bytes = native.read_bytes()
        self.assertEqual(self.attempt('restart')['code'], 'restart_failed')
        self.assertEqual((self.root / 'unbound.conf').read_bytes(), main)
        self.assertEqual(native.read_bytes(), native_bytes)
        self.assertNotIn([apply.CONFIGCTL, 'unbound', 'restart'], self.events)
        self.assertIsNotNone(self.running)

    def test_pidfile_staleness_does_not_prevent_confirmed_kernel_stop(self):
        receipt = self.running.copy()
        with patch.object(apply, 'resolver', return_value=receipt):
            apply.stop_owned(receipt, {})
        self.assertIsNone(self.running)

    def test_native_identity_rejects_same_binary_with_other_config_and_reused_birth(self):
        identity = self.process(10)
        identity['argv'][-1] = '/other/unbound.conf'
        with patch.object(apply, 'process', return_value=identity):
            self.assertIsNone(apply.native_identity(10))
            with self.assertRaises(RuntimeError):
                apply.stop_owned(self.running, {})
        identity = self.process(10)
        identity['birth'] = '999:1234'
        with patch.object(apply, 'process', return_value=identity):
            with self.assertRaises(RuntimeError):
                apply.stop_owned(self.running, {})
        identity = self.process(10)
        identity['uid'] += 1
        with patch.object(apply, 'process', return_value=identity):
            self.assertIsNone(apply.native_identity(10))
        identity = self.process(10)
        identity['argv'].insert(1, '-v')
        with patch.object(apply, 'process', return_value=identity):
            self.assertIsNone(apply.native_identity(10))
        self.assertEqual(self.events, [])

    def test_concurrent_foreign_resolver_during_launch_is_preserved_and_reported(self):
        def foreign(command, **kwargs):
            self.events.append(command)
            self.running = {'pid': 99, 'birth': '999:1234'}
            return SimpleNamespace(pid=11, poll=lambda: 1, wait=lambda timeout: 0)
        with patch.object(apply.subprocess, 'Popen', side_effect=foreign):
            report = self.attempt()
        self.assertEqual(report['code'], 'recovery_failed')
        self.assertEqual(self.running['pid'], 99)
        self.assertEqual([event[1] for event in self.events if event[0] == 'signal'], [10])
        self.assert_restored()

    def test_recovery_cleans_owned_child_before_preserving_foreign_pidfile(self):
        owned = {**self.process(10), 'pid': 11, 'birth': '201:1234'}
        self.running = {'pid': 99, 'birth': '999:1234'}
        foreign = self.process(99)
        alive = [True]
        child = SimpleNamespace(pid=11, poll=lambda: None if alive[0] else 0, wait=lambda timeout: 0)
        def identities(pid):
            return owned if pid == 11 and alive[0] else (foreign if pid == 99 else None)
        def terminate(pid, signum):
            self.assertEqual(pid, 11)
            self.events.append(['signal', pid, signum])
            alive[0] = False
        with patch.object(apply, 'process', side_effect=identities), patch.object(apply.os, 'kill', side_effect=terminate):
            with self.assertRaises(apply.ApplyError) as error:
                apply.recover({'pid': 10, 'birth': '100:1234'},
                              {'stopped': True, 'child': child, 'receipt': apply.identity_receipt(owned)})
        self.assertEqual(error.exception.code, 'recovery_failed')
        self.assertFalse(alive[0])
        self.assertEqual(self.running['pid'], 99)
        self.assertEqual(len(self.events), 1)

    def test_start_never_overwrites_live_foreign_configuration_pid_slot(self):
        foreign = {**self.process(10), 'argv': [apply.UNBOUND, '-c', '/foreign/unbound.conf']}
        with patch.object(apply, 'pidfile_identity', return_value=foreign):
            with self.assertRaises(RuntimeError):
                apply.start_owned({'stopped': True})
        self.assertEqual(self.events, [])

    def test_failed_recovery_launch_cleans_its_own_live_child(self):
        self.running = None
        def timeout(attempt, **kwargs):
            self.running = {'pid': 11, 'birth': '201:1234'}
            attempt['receipt'] = self.running.copy()
            attempt['child'] = SimpleNamespace(pid=11, poll=lambda: None if self.running else 0, wait=lambda timeout: 0)
            raise RuntimeError('isolated recovery launch timeout')
        with patch.object(apply, 'start_owned', side_effect=timeout):
            with self.assertRaises(apply.ApplyError) as error:
                apply.recover({'pid': 10, 'birth': '100:1234'}, {'stopped': True})
        self.assertEqual(error.exception.code, 'recovery_failed')
        self.assertIsNone(self.running)
        self.assertEqual([event[1] for event in self.events if event[0] == 'signal'], [11])


if __name__ == '__main__':
    unittest.main()
