#!/usr/local/bin/python3
"""Validate owned DNS fragments, avoid redundant restarts, and recover failures."""
import base64
import fcntl
import hashlib
import json
import os
from pathlib import Path
import pwd
from process_identity import process
import re
import secrets
import shlex
import signal
import stat
import subprocess
import sys
import tempfile
import time

FRAGMENT = Path('/usr/local/etc/unbound.opnsense.d/custom-options.conf')
RUNTIME = Path('/var/unbound/etc/custom-options.conf')
ROOT = Path('/var/unbound')
STATE = Path('/var/db/os-unboundcustom')
PIDFILE = Path('/var/run/unbound.pid')
CONFIGCTL = '/usr/local/sbin/configctl'
CHECKCONF = '/usr/local/sbin/unbound-checkconf'
UNBOUND = '/usr/local/sbin/unbound'
TEMPLATE_CTL = '/usr/local/opnsense/service/template_ctl.py'
MARKER = b'# Generated by os-unboundcustom.'
LIMIT = 16 * 1024 * 1024


class ApplyError(Exception):
    def __init__(self, code, detail):
        super().__init__(detail)
        self.code = code


def run(command, timeout=90, cwd=None):
    try:
        result = subprocess.run(command, capture_output=True, timeout=timeout, cwd=cwd)
    except (OSError, subprocess.TimeoutExpired) as error:
        raise RuntimeError(str(error)) from error
    if result.returncode:
        raise RuntimeError(result.stderr.decode(errors='replace').strip() or
                           result.stdout.decode(errors='replace').strip() or
                           'Command exited with status %d' % result.returncode)
    return result.stdout


def snapshot(path):
    """Read one stable regular file without following its final path component."""
    path = Path(path)
    try:
        directory = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
    except FileNotFoundError:
        return None
    try:
        try:
            descriptor = os.open(path.name, os.O_RDONLY | os.O_NONBLOCK | os.O_NOFOLLOW,
                                 dir_fd=directory)
        except FileNotFoundError:
            return None
        try:
            before = os.fstat(descriptor)
            if not stat.S_ISREG(before.st_mode) or before.st_size > LIMIT:
                raise RuntimeError('Expected a bounded regular file: %s' % path)
            chunks = []
            remaining = before.st_size
            while remaining:
                chunk = os.read(descriptor, min(remaining, 1024 * 1024))
                if not chunk:
                    raise RuntimeError('A file changed while it was being read: %s' % path)
                chunks.append(chunk)
                remaining -= len(chunk)
            if os.read(descriptor, 1):
                raise RuntimeError('A file changed while it was being read: %s' % path)
            after = os.fstat(descriptor)
            current = os.stat(path.name, dir_fd=directory, follow_symlinks=False)
            identity = lambda info: (info.st_dev, info.st_ino, info.st_size,
                                     info.st_mtime_ns, info.st_ctime_ns)
            if identity(before) != identity(after) or identity(after) != identity(current):
                raise RuntimeError('A file changed while it was being read: %s' % path)
            data = b''.join(chunks)
            return {'data': base64.b64encode(data).decode(),
                    'mode': stat.S_IMODE(after.st_mode), 'uid': after.st_uid, 'gid': after.st_gid}
        finally:
            os.close(descriptor)
    finally:
        os.close(directory)


def content(record):
    return base64.b64decode(record['data'], validate=True) if record else b''


def active(record):
    return any(line.strip() and not line.lstrip().startswith(b'#')
               for line in content(record).splitlines())


def atomic(path, data, mode=0o600, uid=None, gid=None):
    """Replace a file durably through a pinned, non-symlink parent directory."""
    path = Path(path)
    if (uid is None) != (gid is None):
        raise ValueError('A file owner requires both a UID and GID.')
    directory = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
    temporary = '.%s.%s' % (path.name, secrets.token_hex(12))
    descriptor = None
    created = False
    try:
        descriptor = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_EXCL |
                             os.O_NOFOLLOW, 0o600, dir_fd=directory)
        created = True
        with os.fdopen(descriptor, 'wb') as output:
            descriptor = None
            if uid is not None:
                os.fchown(output.fileno(), uid, gid)
            os.fchmod(output.fileno(), mode)
            output.write(data)
            output.flush()
            os.fsync(output.fileno())
        os.replace(temporary, path.name, src_dir_fd=directory, dst_dir_fd=directory)
        os.fsync(directory)
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if created:
            try:
                os.unlink(temporary, dir_fd=directory)
            except FileNotFoundError:
                pass
        os.close(directory)


def restore(path, record):
    if record is None:
        path = Path(path)
        directory = os.open(path.parent, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
        try:
            try:
                os.unlink(path.name, dir_fd=directory)
            except FileNotFoundError:
                pass
            os.fsync(directory)
        finally:
            os.close(directory)
    else:
        atomic(path, content(record), record['mode'], record['uid'], record['gid'])


def rooted(root, path):
    return Path(root) / str(path).lstrip('/')


def prepare_state():
    """Create and pin the root-only state directory without following a link."""
    try:
        parent = os.open(STATE.parent, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
        try:
            try:
                os.mkdir(STATE.name, 0o700, dir_fd=parent)
                os.fsync(parent)
            except FileExistsError:
                pass
            directory = os.open(STATE.name, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW,
                                dir_fd=parent)
            try:
                info = os.fstat(directory)
                if info.st_uid != 0:
                    raise ApplyError('state_failed', 'The state directory must be owned by root.')
                os.fchmod(directory, 0o700)
                os.fsync(directory)
            finally:
                os.close(directory)
        finally:
            os.close(parent)
    except ApplyError:
        raise
    except OSError as error:
        raise ApplyError('state_failed', 'The private state directory is unsafe or unavailable.') from error


def render_fragment():
    """Render the template outside every live Unbound include path."""
    with tempfile.TemporaryDirectory(prefix='.template-', dir=STATE) as temporary:
        stage = Path(temporary)
        output = run([TEMPLATE_CTL, '-r', str(stage), 'OPNsense/Unboundcustom'])
        if output.strip() != b'templates...done':
            raise RuntimeError('The Unbound custom options template renderer reported failure.')
        rendered = snapshot(rooted(stage, FRAGMENT))
        if rendered is None:
            raise RuntimeError('The Unbound custom options template did not produce its declared target.')
        return rendered


def candidate_main(data, include_directory):
    """Redirect the one native OPNsense include glob to a private candidate tree."""
    source = str(ROOT / 'etc/*.conf')
    target = str(include_directory / '*.conf')
    output = []
    replacements = 0
    try:
        lines = data.decode('utf-8').splitlines(keepends=True)
    except UnicodeError as error:
        raise RuntimeError('The native Unbound configuration is not valid UTF-8.') from error
    for line in lines:
        body = line.rstrip('\r\n')
        if not re.match(r'^\s*include\s*:', body):
            output.append(line)
            continue
        try:
            parts = shlex.split(body, comments=True)
        except ValueError as error:
            raise RuntimeError('The native Unbound include line is invalid.') from error
        if parts == ['include:', source]:
            indent = body[:len(body) - len(body.lstrip())]
            ending = line[len(body):]
            output.append(indent + 'include: ' + target + ending)
            replacements += 1
        else:
            output.append(line)
    if replacements != 1:
        raise RuntimeError('The native Unbound configuration does not have one recognized include directory.')
    return ''.join(output).encode('utf-8')


def validate_candidate(runtime):
    """Check a complete candidate without publishing any active resolver file."""
    with tempfile.TemporaryDirectory(prefix='.check-', dir=STATE) as temporary:
        stage = Path(temporary)
        include_directory = stage / 'etc'
        include_directory.mkdir(mode=0o700)
        sources = sorted((ROOT / 'etc').glob('*.conf'))
        if len(sources) > 4096:
            raise RuntimeError('The native Unbound include directory is too large.')
        total = 0
        for source in sources:
            if source == RUNTIME:
                continue
            record = snapshot(source)
            total += len(content(record))
            if total > LIMIT:
                raise RuntimeError('The native Unbound include closure is too large.')
            atomic(include_directory / source.name, content(record), record['mode'])
        if runtime is not None:
            total += len(content(runtime))
            if total > LIMIT:
                raise RuntimeError('The native Unbound include closure is too large.')
            atomic(include_directory / RUNTIME.name, content(runtime), runtime['mode'])
        main = snapshot(ROOT / 'unbound.conf')
        if main is None:
            raise RuntimeError('The native Unbound configuration is unavailable.')
        path = stage / 'unbound.conf'
        atomic(path, candidate_main(content(main), include_directory), main['mode'])
        run([CHECKCONF, str(path)], cwd=ROOT)


def closure():
    """Hash the bounded include closure; unknown includes never permit a no-op."""
    try:
        root = ROOT.resolve()
        pending = [ROOT / 'unbound.conf']
        files = {}
        total = 0
        while pending:
            path = pending.pop()
            resolved = path.resolve(strict=True)
            if resolved in files and not path.is_symlink():
                continue
            if not resolved.is_relative_to(root) or path.is_symlink():
                return None
            record = snapshot(path)
            data = content(record)
            total += len(data)
            if record is None or len(files) >= 4096 or total > LIMIT:
                return None
            files[resolved] = data
            for line in data.decode('utf-8').splitlines():
                if not re.match(r'^\s*include(?:-toplevel)?\s*:', line):
                    continue
                parts = shlex.split(line, comments=True)
                if len(parts) != 2 or parts[0] not in ('include:', 'include-toplevel:'):
                    return None
                include = Path(parts[1])
                if not include.is_absolute() or not include.parent.resolve().is_relative_to(root):
                    return None
                if include.name == '*.conf':
                    pending.extend(sorted(include.parent.glob('*.conf')))
                elif any(character in str(include) for character in '*?['):
                    return None
                else:
                    pending.append(include)
        digest = hashlib.sha256()
        for path, data in sorted(files.items()):
            digest.update(str(path.relative_to(root)).encode() + b'\0')
            digest.update(len(data).to_bytes(8, 'big') + data)
        return digest.hexdigest()
    except (OSError, ValueError, UnicodeError, RuntimeError):
        return None


def native_identity(pid):
    """Require the native account, executable, and one supported exact argv."""
    identity = process(pid)
    if not identity or identity['executable'] != UNBOUND:
        return None
    try:
        uid = pwd.getpwnam('unbound').pw_uid
    except KeyError as error:
        raise RuntimeError('The native Unbound account is unavailable.') from error
    expected = [UNBOUND, '-c', str(ROOT / 'unbound.conf')]
    foreground = [UNBOUND, '-d', '-c', str(ROOT / 'unbound.conf')]
    if identity.get('uid') != uid or identity['argv'] not in (expected, foreground):
        return None
    return identity


def identity_receipt(identity):
    return {'pid': identity['pid'], 'birth': identity['birth']} if identity else None


def pidfile_identity():
    """An occupied native PID slot may belong to a foreign configuration or binary."""
    try:
        record = snapshot(PIDFILE)
        if record is None:
            return None
        if len(content(record)) > 11:
            raise RuntimeError('The native resolver PID file is malformed.')
        text = content(record).decode('ascii')
    except UnicodeError as error:
        raise RuntimeError('The native resolver PID file is malformed.') from error
    except FileNotFoundError:
        return None
    if not re.fullmatch(r'[1-9][0-9]{0,9}\n?', text) or int(text) >= 2147483648:
        raise RuntimeError('The native resolver PID file is malformed.')
    return process(int(text))


def resolver():
    """A receipt is valid only for the same actual native Unbound process."""
    identity = pidfile_identity()
    if identity is None:
        return None
    native = native_identity(identity['pid'])
    if native is not None:
        return identity_receipt(native)
    if process(identity['pid']) is None:
        return None
    raise RuntimeError('The native resolver PID file does not reference the expected Unbound process.')


def validate():
    run([CHECKCONF, 'unbound.conf'], cwd=ROOT)


def read_receipt(path, paths):
    """Existing unsupported journals never authorize a mutation or legacy removal."""
    try:
        record = snapshot(path)
        if record is None:
            return None
        if record['uid'] != os.geteuid() or record['mode'] != 0o600:
            raise ValueError('Unsafe receipt ownership or permissions')
        receipt = json.loads(content(record))
        if not isinstance(receipt, dict) or set(receipt) != {'owned', 'closure', 'resolver'}:
            raise ValueError('Unsupported receipt structure')
        owned = receipt['owned']
        if not isinstance(owned, dict) or set(owned) != {str(item) for item in paths}:
            raise ValueError('Unsupported ownership structure')
        for item in owned.values():
            if item is None:
                continue
            if not isinstance(item, dict) or set(item) != {'data', 'mode', 'uid', 'gid'}:
                raise ValueError('Unsupported file receipt')
            if not isinstance(item['data'], str) or len(content(item)) > LIMIT:
                raise ValueError('Invalid file content receipt')
            if any(type(item[key]) is not int or not 0 <= item[key] <= upper
                   for key, upper in [('mode', 0o7777), ('uid', 4294967295), ('gid', 4294967295)]):
                raise ValueError('Invalid file metadata receipt')
        digest = receipt['closure']
        if digest is not None and (not isinstance(digest, str) or not re.fullmatch(r'[0-9a-f]{64}', digest)):
            raise ValueError('Invalid configuration receipt')
        owner = receipt['resolver']
        if owner is not None and (not isinstance(owner, dict) or set(owner) != {'pid', 'birth'} or
                type(owner['pid']) is not int or not 0 < owner['pid'] < 2147483648 or
                not isinstance(owner['birth'], str) or not re.fullmatch(r'[1-9][0-9]*:[0-9]{1,6}', owner['birth'])):
            raise ValueError('Invalid resolver receipt')
        return receipt
    except (OSError, RuntimeError, ValueError, TypeError, UnicodeError) as error:
        raise ApplyError('state_failed', 'The existing configuration receipt is invalid; files and DNS were preserved.') from error


def stop_owned(receipt, attempt, timeout=5):
    """Do not use a stale pidfile to decide whether the original process exited."""
    if resolver() != receipt or identity_receipt(native_identity(receipt['pid'])) != receipt:
        raise RuntimeError('The resolver was stopped or replaced concurrently; no process was signalled.')
    os.kill(receipt['pid'], signal.SIGTERM)
    attempt['term_sent'] = True
    deadline = time.monotonic() + timeout
    while True:
        actual = process(receipt['pid'])
        if not actual or identity_receipt(actual) != receipt:
            return
        if time.monotonic() >= deadline:
            raise RuntimeError('The original resolver did not stop within the bounded timeout.')
        time.sleep(0.05)


def start_owned(attempt, timeout=5):
    """Foreground mode supplies a kernel-verifiable child PID without daemon adoption."""
    if pidfile_identity():
        raise RuntimeError('A concurrent resolver was preserved; no new resolver was started.')
    child = subprocess.Popen([UNBOUND, '-d', '-c', str(ROOT / 'unbound.conf')],
                             cwd=ROOT, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
                             stderr=subprocess.DEVNULL, start_new_session=True)
    attempt['child'] = child
    attempt['receipt'] = None
    deadline = time.monotonic() + timeout
    stable_since = None
    while True:
        code = child.poll()
        if code is not None:
            raise RuntimeError('The resolver exited during startup (status %d).' % code)
        identity = native_identity(child.pid)
        if identity:
            attempt['receipt'] = identity_receipt(identity)
        current = identity_receipt(pidfile_identity())
        if current and current != attempt['receipt']:
            raise RuntimeError('A concurrent resolver replaced the startup PID file and was preserved.')
        if current and identity and not identity.get('stopped', False):
            if stable_since is None:
                stable_since = time.monotonic()
            # PID files are written before initialization; reject immediate startup failures.
            if time.monotonic() - stable_since >= 0.3:
                return current
        else:
            stable_since = None
        if time.monotonic() >= deadline:
            raise RuntimeError('The launched resolver did not report running within the bounded timeout.')
        time.sleep(0.05)


def cleanup_child(attempt):
    """Stop only an exact unreaped child, independently of the shared PID file."""
    child = attempt.get('child')
    owned = attempt.get('receipt')
    if child and child.poll() is None:
        actual = native_identity(child.pid)
        if not owned or identity_receipt(actual) != owned:
            raise RuntimeError('The launched process identity changed; recovery preserved it.')
        # The launch handle supplies PID continuity even if a foreign pidfile was written.
        os.kill(child.pid, signal.SIGTERM)
        try:
            child.wait(timeout=5)
        except subprocess.TimeoutExpired:
            if identity_receipt(native_identity(child.pid)) != owned:
                raise RuntimeError('The launched resolver identity changed during recovery.')
            os.kill(child.pid, signal.SIGKILL)
            child.wait(timeout=5)


def recover(was_running, attempt):
    """Recover only our child or an empty slot after our confirmed original stop."""
    if not was_running:
        return ''
    if resolver() == was_running and not attempt['stopped']:
        return ''
    if not attempt['stopped'] and attempt.get('term_sent') and not process(was_running['pid']):
        attempt['stopped'] = True
    owned = attempt.get('receipt')
    try:
        cleanup_child(attempt)
        current = identity_receipt(pidfile_identity())
        if current and current != owned:
            raise RuntimeError('A concurrent resolver was preserved; recovery could not restart it.')
        if not attempt['stopped']:
            raise RuntimeError('The original resolver was changed concurrently; recovery did not start DNS.')
        validate()
        restored = {'stopped': True}
        try:
            start_owned(restored)
        except (OSError, RuntimeError):
            cleanup_child(restored)
            raise
        return ' The previous resolver configuration was restored and started.'
    except (OSError, RuntimeError, subprocess.TimeoutExpired) as error:
        raise ApplyError('recovery_failed', str(error)) from error


def transaction(remove=False):
    paths = (FRAGMENT, RUNTIME)
    receipt_path = STATE / 'applied.json'
    receipt = read_receipt(receipt_path, paths)
    before = {str(path): snapshot(path) for path in paths}
    was_running = resolver()
    previous = closure()
    if remove:
        # Exact receipts preserve subsequent administrator edits. Legacy marked
        # fragments are recognizable, but arbitrary same-named files are not ours.
        targets = dict(before)
        for path in paths:
            record = before[str(path)]
            owned = receipt['owned'][str(path)] if receipt is not None else None
            if record and ((owned is not None and owned == record) or
                           (receipt is None and content(record).lstrip().startswith(MARKER))):
                targets[str(path)] = None
        if before == targets:
            if receipt is not None:
                payload = {**receipt, 'owned': {str(path): None for path in paths}}
                atomic(receipt_path, (json.dumps(payload, sort_keys=True) + '\n').encode())
            return {'status': 'ok', 'code': 'success', 'detail': '', 'restarted': False}
    else:
        try:
            generated = render_fragment()
        except RuntimeError as error:
            raise ApplyError('template_failed', str(error)) from error
        try:
            user = pwd.getpwnam('unbound')
            runtime = {'data': base64.b64encode(content(generated)).decode(), 'mode': 0o640,
                       'uid': user.pw_uid, 'gid': user.pw_gid}
            targets = {str(FRAGMENT): generated, str(RUNTIME): runtime}
        except (OSError, RuntimeError, KeyError, TypeError) as error:
            raise ApplyError('stage_failed', str(error)) from error
    try:
        validate_candidate(targets[str(RUNTIME)])
    except (OSError, RuntimeError) as error:
        raise ApplyError('validation_failed', str(error)) from error
    published = []
    try:
        for path in paths:
            key = str(path)
            if targets[key] == before[key]:
                continue
            if snapshot(path) != before[key]:
                raise RuntimeError('A resolver fragment changed concurrently; live files were preserved.')
            restore(path, targets[key])
            published.append(path)
        staged = {str(path): snapshot(path) for path in paths}
        if staged != targets:
            raise RuntimeError('A resolver fragment did not match its validated candidate.')
    except (OSError, RuntimeError) as error:
        recovery_errors = []
        for path in reversed(published):
            try:
                if snapshot(path) == targets[str(path)]:
                    restore(path, before[str(path)])
                elif snapshot(path) != before[str(path)]:
                    recovery_errors.append('Concurrent change preserved: %s' % path)
            except (OSError, RuntimeError) as rollback_error:
                recovery_errors.append(str(rollback_error))
        if recovery_errors:
            raise ApplyError('recovery_failed', str(error) + ' ' + '; '.join(recovery_errors)) from error
        raise ApplyError('stage_failed', str(error)) from error
    attempt = {'stopped': False}
    restart = False
    try:
        try:
            validate()
        except RuntimeError as error:
            raise ApplyError('validation_failed', str(error)) from error
        current = closure()
        effective_change = (before[str(RUNTIME)] != staged[str(RUNTIME)] and
                            (active(before[str(RUNTIME)]) or active(staged[str(RUNTIME)])))
        same_loaded_config = (current is not None and current == previous == (receipt or {}).get('closure')
                              and was_running == (receipt or {}).get('resolver') and was_running is not None)
        inactive = not active(before[str(RUNTIME)]) and not active(staged[str(RUNTIME)])
        restart = bool(was_running and (effective_change or (not inactive and not same_loaded_config)))
        if restart:
            try:
                stop_owned(was_running, attempt)
                attempt['stopped'] = True
                start_owned(attempt)
            except (OSError, RuntimeError) as error:
                raise ApplyError('restart_failed', str(error)) from error
        # Direct startup never regenerates the main configuration or other includes.
        owned = ({str(path): None for path in paths} if remove else
                 {str(path): snapshot(path) for path in paths})
        payload = {'owned': owned, 'closure': closure() if restart or same_loaded_config else None,
                   'resolver': resolver() if restart or same_loaded_config else None}
        encoded = (json.dumps(payload, sort_keys=True) + '\n').encode()
        if len(encoded) > LIMIT:
            raise ApplyError('state_failed', 'The configuration receipt exceeds its bounded size.')
        atomic(receipt_path, encoded)
        return {'status': 'ok', 'code': 'success', 'detail': '', 'restarted': restart}
    except (ApplyError, OSError, RuntimeError) as error:
        recovery_errors = []
        for path in paths:
            try:
                if snapshot(path) == staged[str(path)]:
                    restore(path, before[str(path)])
                elif snapshot(path) != before[str(path)]:
                    recovery_errors.append('Concurrent change preserved: %s' % path)
            except (OSError, RuntimeError) as rollback_error:
                recovery_errors.append(str(rollback_error))
        detail = str(error)
        try:
            if restart and (attempt.get('term_sent') or attempt.get('child')):
                detail += recover(was_running, attempt)
        except ApplyError as recovery_error:
            recovery_errors.append(str(recovery_error))
        # Atomic journal publication occurs last; failed transactions retain the
        # previous ownership receipt instead of turning later removal into legacy.
        if recovery_errors:
            raise ApplyError('recovery_failed', detail + ' ' + '; '.join(recovery_errors)) from error
        raise ApplyError(error.code if isinstance(error, ApplyError) else 'apply_failed', detail) from error


def main():
    try:
        prepare_state()
        directory = os.open(STATE, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
        try:
            descriptor = os.open('apply.lock', os.O_CREAT | os.O_RDWR | os.O_NONBLOCK |
                                 os.O_NOFOLLOW, 0o600, dir_fd=directory)
        finally:
            os.close(directory)
        with os.fdopen(descriptor, 'r+') as lock:
            info = os.fstat(lock.fileno())
            if not stat.S_ISREG(info.st_mode) or info.st_uid != 0:
                raise ApplyError('state_failed', 'The transaction lock must be a regular root-owned file.')
            os.fchmod(lock.fileno(), 0o600)
            try:
                fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError:
                raise ApplyError('busy', 'Another DNS configuration transaction is running.')
            result = transaction(remove=len(sys.argv) > 1 and sys.argv[1] == 'remove')
    except (ApplyError, OSError, RuntimeError) as error:
        result = {'status': 'failed', 'code': error.code if isinstance(error, ApplyError) else 'apply_failed',
                  'detail': str(error)}
    print(json.dumps(result))
    return 1 if result['status'] != 'ok' and len(sys.argv) > 1 and sys.argv[1] in ('remove', 'install') else 0


if __name__ == '__main__':
    sys.exit(main())
