#!/usr/local/bin/php
<?php

/* Integrate only the plugin's own DNS forwarder and TUN interface. */
const FORWARD_UUID = 'b126bf65-a985-49ca-a9d2-16f156aac198';
const RULE_UUID = '5a73c3dc-69b1-4e15-89cb-b542aa2c1154';
const FAKE_IP_CIDR = '198.18.0.0/15';
/* Unbound's drop-in directory: OPNsense copies every .conf placed here into
   the chroot on reconfigure. Unbound keeps the LAST forward zone it reads for
   a name, so the name has to sort behind the generated dot.conf to win the
   root; an earlier version used a name that sorted ahead of it and was
   silently ignored. */
const FORWARD_PATH = '/usr/local/etc/unbound.opnsense.d/zz-mihomo.conf';
const FORWARD_LEGACY_PATH = '/usr/local/etc/unbound.opnsense.d/00-mihomo.conf';

function mihomoForwardFile(): string
{
    /* Rooted like every other path this helper writes. Without it the test
       harness, which points OS_MIHOMO_ROOT at a temporary directory, would
       still create and delete the real forward zone on the machine running
       the tests -- and on a router that is the file the resolver reads. */
    return rtrim(getenv('OS_MIHOMO_ROOT') ?: '', '/') . FORWARD_PATH;
}

function mihomoForwardLegacyFile(): string
{
    return rtrim(getenv('OS_MIHOMO_ROOT') ?: '', '/') . FORWARD_LEGACY_PATH;
}

function mihomoChild(DOMDocument $doc, DOMElement $parent, string $name, string $value = ''): DOMElement
{
    foreach ($parent->childNodes as $node) {
        if ($node instanceof DOMElement && $node->tagName === $name) {
            $node->nodeValue = $value;
            return $node;
        }
    }
    $node = $doc->createElement($name);
    if ($value !== '') {
        $node->appendChild($doc->createTextNode($value));
    }
    $parent->appendChild($node);
    return $node;
}

function mihomoForwardZone(bool $enabled, bool $fallback, bool $validating = false): bool
{
    $path = mihomoForwardFile();
    $changed = false;
    /* The name this file used to carry never won the root zone, so a leftover
       copy is dead weight at best and a second root zone at worst. */
    $legacy = mihomoForwardLegacyFile();
    if (file_exists($legacy) && unlink($legacy)) {
        $changed = true;
    }
    /* A validating resolver cannot accept what Mihomo answers: fake-ip records
       carry no signature, so every signed zone fails validation. Telling
       Unbound to skip validation for the root is the one thing that would make
       it work and is exactly the configuration that stops the resolver
       starting, so the forward zone is simply not written while validation is
       on. Domain based routing still comes from the sniffer. */
    if ($validating) {
        $enabled = false;
    }
    /* The forward zone is a file rather than an entry in the operator's Unbound
       configuration. An entry carrying the root as its domain makes OPNsense
       generate domain-insecure: "." alongside it -- a negative trust anchor for
       a zone that already has one from auto-trust-anchor-file. Unbound then
       finds the anchor for '.' presented twice, the validator fails to
       initialise, and the resolver does not start at all. */
    if (!$enabled) {
        if (!file_exists($path)) {
            return $changed;
        }
        if (!unlink($path)) {
            throw new RuntimeException('Unable to remove the Mihomo forward zone.');
        }
        return true;
    }
    $lines = ['# Generated by os-mihomo. Removed when transparent routing is off.',
              'server:', '  do-not-query-localhost: no', '',
              'forward-zone:', '  name: "."', '  forward-addr: 127.0.0.1@1053'];
    if ($fallback) {
        $lines[] = '  forward-first: yes';
    }
    $body = implode("\n", $lines) . "\n";
    if (@file_get_contents($path) === $body) {
        return $changed;
    }
    if (!is_dir(dirname($path)) && !mkdir(dirname($path), 0755, true)) {
        throw new RuntimeException('The Unbound drop-in directory is missing.');
    }
    $temporary = tempnam(dirname($path), '.mihomo-zone-');
    if ($temporary === false || file_put_contents($temporary, $body) === false
        || !chmod($temporary, 0644) || !rename($temporary, $path)) {
        if ($temporary !== false) {
            @unlink($temporary);
        }
        throw new RuntimeException('Unable to write the Mihomo forward zone.');
    }
    return true;
}

function mihomoPersist(string $path, array $state): void
{
    $temporary = tempnam(dirname($path), '.mihomo-state-');
    if ($temporary === false || file_put_contents($temporary, json_encode($state, JSON_THROW_ON_ERROR)) === false) {
        throw new RuntimeException('Unable to write integration state.');
    }
    chmod($temporary, 0600);
    if (!rename($temporary, $path)) {
        @unlink($temporary);
        throw new RuntimeException('Unable to persist integration state.');
    }
}

function mihomoState(string $path): ?array
{
    if (!file_exists($path)) {
        return null;
    }
    $value = json_decode((string)file_get_contents($path), true, 512, JSON_THROW_ON_ERROR);
    if (!is_array($value)) {
        throw new RuntimeException('Invalid integration state.');
    }
    return $value;
}

function mihomoEnsureTun(DOMDocument $doc, DOMXPath $xpath, string $statePath): void
{
    $saved = mihomoState($statePath);
    $interfaces = $xpath->query('/opnsense/interfaces')->item(0);
    $filter = $xpath->query('/opnsense/filter')->item(0);
    if (!$interfaces instanceof DOMElement || !$filter instanceof DOMElement) {
        throw new RuntimeException('The interface or firewall model is missing.');
    }
    $target = '';
    $maximum = -1;
    foreach ($interfaces->childNodes as $node) {
        if (!$node instanceof DOMElement) {
            continue;
        }
        if (preg_match('/^opt([0-9]+)$/', $node->tagName, $matches)) {
            $maximum = max($maximum, (int)$matches[1]);
        }
        if (trim($xpath->evaluate('string(./if)', $node)) === 'tun_mihomo') {
            $target = $node->tagName;
        }
    }
    $created = $target === '';
    $target = $target ?: 'opt' . ($maximum + 1);
    $existingRule = $xpath->query('/opnsense/filter/rule[@uuid="' . RULE_UUID . '"]')->item(0);
    if ($saved === null) {
        mihomoPersist($statePath, ['interface' => $target, 'created_interface' => $created, 'created_rule' => !$existingRule]);
    } elseif ($saved['interface'] !== $target && !$created) {
        throw new RuntimeException('The Mihomo interface assignment changed.');
    }
    if ($saved !== null && $created) {
        $target = $saved['interface'];
        if ($xpath->query('/opnsense/interfaces/' . $target)->length > 0) {
            throw new RuntimeException('The saved interface assignment is occupied.');
        }
    }
    if ($created) {
        $interface = $doc->createElement($target);
        $interfaces->appendChild($interface);
        mihomoChild($doc, $interface, 'if', 'tun_mihomo');
        mihomoChild($doc, $interface, 'descr', 'Mihomo TUN');
        mihomoChild($doc, $interface, 'enable', '1');
    }
    if (!$existingRule) {
        $rule = $doc->createElement('rule');
        $rule->setAttribute('uuid', RULE_UUID);
        $filter->appendChild($rule);
        mihomoChild($doc, $rule, 'type', 'pass');
        mihomoChild($doc, $rule, 'interface', $target);
        mihomoChild($doc, $rule, 'ipprotocol', 'inet');
        $source = mihomoChild($doc, $rule, 'source');
        mihomoChild($doc, $source, 'network', $target);
        $destination = mihomoChild($doc, $rule, 'destination');
        mihomoChild($doc, $destination, 'any');
        mihomoChild($doc, $rule, 'descr', 'Mihomo TUN Allow');
    }
}

function mihomoCronCommand(string $command): bool
{
    return in_array($command, ['mihomo sub-update', 'mihomolocal update', 'mihomolocal repair',
        '/usr/bin/mihomo_sub', '/usr/local/etc/mihomo/sub/sub.sh'], true);
}

function mihomoRemoveTun(DOMXPath $xpath, string $path): void
{
    $tun = mihomoState($path);
    if ($tun !== null && $tun['created_interface']) {
        $node = $xpath->query('/opnsense/interfaces/' . $tun['interface'])->item(0);
        if ($node instanceof DOMElement && trim($xpath->evaluate('string(./if)', $node)) === 'tun_mihomo') {
            $node->parentNode->removeChild($node);
        }
    }
    if ($tun !== null && $tun['created_rule']) {
        foreach ($xpath->query('/opnsense/filter/rule[@uuid="' . RULE_UUID . '"]') as $node) {
            $node->parentNode->removeChild($node);
        }
    }
}

$mode = $argv[1] ?? '';
// The old package may call the replacement helper during its removal phase.
if ($mode === 'uninstall') {
    $mode = 'disable';
}
$fallback = ($argv[2] ?? '1') === '1';
if (!in_array($mode, ['enable', 'enable-tun', 'disable', 'remove', 'restore-cron'], true)) {
    fwrite(STDERR, "usage: setup_unbound.php enable|enable-tun|disable|remove|restore-cron [fallback:0|1]\n");
    exit(64);
}
/* Removing the forward zone comes before anything that can fail. Everything
   below can throw -- an Unbound model the operator's restored backup no longer
   matches, a truncated state file -- and the caller stops the core regardless,
   so a removal left until after those checks can leave Unbound forwarding the
   root to a port with nothing behind it. */
$earlyZoneChange = false;
if (in_array($mode, ['disable', 'remove'], true)) {
    $earlyZoneChange = mihomoForwardZone(false, $fallback);
}
$root = rtrim(getenv('OS_MIHOMO_ROOT') ?: '', '/');
$stateDir = $root . '/var/db/os-mihomo';
$dnsStatePath = $stateDir . '/dns-state.json';
$tunStatePath = $stateDir . '/tun-state.json';
$configPath = $root . '/conf/config.xml';
if (!is_dir($stateDir) && !mkdir($stateDir, 0700, true)) {
    fwrite(STDERR, "Unable to create integration state directory.\n");
    exit(1);
}
$native = null;
$handle = null;
try {
    if ($root === '') {
        /* config.inc stamps each revision with the invoking user and reaches for
           shell_safe() to do it, which lives in util.inc. Writing the
           configuration without it fails at the moment of the write. */
        require_once('/usr/local/etc/inc/util.inc');
        require_once('/usr/local/etc/inc/config.inc');
        $native = OPNsense\Core\Config::getInstance();
        $native->lock();
        $doc = dom_import_simplexml($native->object())->ownerDocument;
    } else {
        $handle = fopen($configPath, 'r');
        if ($handle === false || !flock($handle, LOCK_EX)) {
            throw new RuntimeException('Unable to lock configuration.');
        }
        $doc = new DOMDocument();
        $doc->preserveWhiteSpace = true;
        if (!$doc->load($configPath, LIBXML_NONET)) {
            throw new RuntimeException('Unable to read configuration.');
        }
    }
    $before = $doc->saveXML();
    $zoneChanged = false;
    $xpath = new DOMXPath($doc);
    if ($mode === 'restore-cron') {
        $legacyPath = $stateDir . '/migrate/cron.json';
        if (file_exists($legacyPath)) {
            foreach (json_decode((string)file_get_contents($legacyPath), true, 512, JSON_THROW_ON_ERROR) as $item) {
                if (!mihomoCronCommand(trim($item['command'] ?? ''))) {
                    continue;
                }
                $clone = $doc->createElement('item');
                foreach (['minutes', 'hours', 'mday', 'month', 'wday'] as $field) {
                    mihomoChild($doc, $clone, $field, (string)($item[$field] ?? '*'));
                }
                mihomoChild($doc, $clone, 'command', 'mihomo sub-update');
                $cron = $xpath->query('/opnsense/cron')->item(0);
                if (!$cron instanceof DOMElement) {
                    $cron = $doc->createElement('cron');
                    $doc->documentElement->appendChild($cron);
                }
                $duplicate = false;
                foreach ($xpath->query('./item', $cron) as $existing) {
                    $signature = static function ($node) use ($xpath): array {
                        $value = [];
                        foreach (['command', 'minutes', 'hours', 'mday', 'month', 'wday'] as $field) {
                            $value[$field] = trim($xpath->evaluate('string(./' . $field . ')', $node));
                        }
                        return $value;
                    };
                    if ($signature($existing) === $signature($clone)) {
                        $duplicate = true;
                    }
                }
                if (!$duplicate) {
                    $cron->appendChild($clone);
                }
            }
        }
    } elseif ($mode === 'enable-tun') {
        mihomoEnsureTun($doc, $xpath, $tunStatePath);
    } else {
        $unbound = $xpath->query('/opnsense/OPNsense/unboundplus')->item(0);
        $forwarding = $xpath->query('./forwarding/enabled', $unbound)->item(0);
        $private = $xpath->query('./advanced/privateaddress', $unbound)->item(0);
        $dots = $xpath->query('./dots', $unbound)->item(0);
        if (!$unbound instanceof DOMElement || !$forwarding instanceof DOMElement || !$private instanceof DOMElement || !$dots instanceof DOMElement) {
            throw new RuntimeException('The Unbound model is incomplete.');
        }
        $snapshot = mihomoState($dnsStatePath);
        $forwarder = $xpath->query('./dot[@uuid="' . FORWARD_UUID . '"]', $dots)->item(0);
        if ($mode === 'enable') {
            mihomoEnsureTun($doc, $xpath, $tunStatePath);
            if ($snapshot === null) {
                $roots = [];
                foreach ($xpath->query('./dot', $dots) as $dot) {
                    $domain = trim($xpath->evaluate('string(./domain)', $dot));
                    if (in_array($domain, ['', '.'], true) && $dot->getAttribute('uuid') !== FORWARD_UUID) {
                        if ($dot->getAttribute('uuid') === '') {
                            throw new RuntimeException('Existing root DNS entries must have UUIDs.');
                        }
                        $roots[$dot->getAttribute('uuid')] = trim($xpath->evaluate('string(./enabled)', $dot));
                    }
                }
                $snapshot = ['forwarding' => $forwarding->textContent, 'roots' => $roots,
                             'had_fake_ip_private_address' => in_array(FAKE_IP_CIDR, explode(',', $private->textContent), true)];
                mihomoPersist($dnsStatePath, $snapshot);
            }
            $forwarding->nodeValue = '0';
            /* The operator's own root upstreams are left exactly as they are.
               Unbound keeps the first forward zone it reads for a name and logs
               the rest as duplicates, and the entry below is not served over
               TLS, so the template writes it ahead of any DoT entry and queries
               reach Mihomo either way. Disabling the operator's entries would
               buy nothing and would edit configuration that is not ours. */
            $addresses = array_filter(array_map('trim', explode(',', $private->textContent)), static fn($v) => $v !== '' && $v !== FAKE_IP_CIDR);
            $private->nodeValue = implode(',', $addresses);
            /* Earlier versions kept the forward zone here. Drop it on the way
               past so an upgrade stops generating domain-insecure: "." too. */
            if ($forwarder instanceof DOMElement) {
                $dots->removeChild($forwarder);
            }
            $validating = trim($xpath->evaluate('string(./general/dnssec)', $unbound)) === '1';
            $zoneChanged = mihomoForwardZone(true, $fallback, $validating);
        } else {
            if ($forwarder instanceof DOMElement) {
                $dots->removeChild($forwarder);
            }
            $zoneChanged = mihomoForwardZone(false, $fallback) || $earlyZoneChange;
            if ($snapshot !== null) {
                if (trim($forwarding->textContent) === '0') {
                    $forwarding->nodeValue = (string)$snapshot['forwarding'];
                }
                /* Nothing disables these any more; the loop re-enables what an
                   earlier version of the plugin turned off. */
                foreach ($snapshot['roots'] as $uuid => $enabled) {
                    $node = $xpath->query('./dot[@uuid="' . $uuid . '"]', $dots)->item(0);
                    if ($node instanceof DOMElement && trim($xpath->evaluate('string(./enabled)', $node)) === '0') {
                        mihomoChild($doc, $node, 'enabled', (string)$enabled);
                    }
                }
                if ($snapshot['had_fake_ip_private_address']) {
                    $addresses = array_values(array_filter(array_map('trim', explode(',', $private->textContent))));
                    if (!in_array(FAKE_IP_CIDR, $addresses, true)) {
                        $addresses[] = FAKE_IP_CIDR;
                        $private->nodeValue = implode(',', $addresses);
                    }
                }
            }
            if ($mode === 'remove') {
                foreach ($xpath->query('/opnsense/cron/item') as $item) {
                    if (mihomoCronCommand(trim($xpath->evaluate('string(./command)', $item)))) {
                        $item->parentNode->removeChild($item);
                    }
                }
            }
            mihomoRemoveTun($xpath, $tunStatePath);
        }
    }
    if ($before !== $doc->saveXML()) {
        if ($native !== null) {
            $native->save(make_config_revision_entry('Update Mihomo transparent integration'));
        } else {
            $temporary = tempnam(dirname($configPath), '.mihomo-config-');
            if ($temporary === false || $doc->save($temporary) === false || !rename($temporary, $configPath)) {
                throw new RuntimeException('Unable to save configuration.');
            }
        }
    }
    if (in_array($mode, ['disable', 'remove'], true)) {
        @unlink($dnsStatePath);
        @unlink($tunStatePath);
    }
    if ($mode === 'restore-cron') {
        @unlink($stateDir . '/migrate/cron.json');
        @unlink($stateDir . '/migrate/config.xml');
    }
    echo $before !== $doc->saveXML() || $zoneChanged || $earlyZoneChange
        ? "Mihomo integration updated.\n" : "Mihomo integration unchanged.\n";
} catch (Throwable $error) {
    fwrite(STDERR, "Mihomo integration failed. Existing DNS state is retained for recovery.\n");
    exit(1);
} finally {
    if ($native !== null) {
        $native->unlock();
    }
    if (is_resource($handle)) {
        fclose($handle);
    }
}
