[get]
command:/usr/local/bin/php /usr/local/opnsense/scripts/speedtest/api.php get
parameters:%s
type:script_output
message:Speedtest get

[set]
command:/usr/local/bin/php /usr/local/opnsense/scripts/speedtest/api.php set
parameters:%s
type:script_output
message:Speedtest set

[servers]
command:/usr/local/bin/php /usr/local/opnsense/scripts/speedtest/api.php servers
parameters:%s
type:script_output
message:Speedtest servers

[refresh]
command:/usr/local/bin/php /usr/local/opnsense/scripts/speedtest/api.php refresh
parameters:%s
type:script_output
message:Speedtest refresh

[run]
command:/usr/local/bin/php /usr/local/opnsense/scripts/speedtest/api.php run
parameters:%s
type:script_output
message:Speedtest run

[progress]
command:/usr/local/bin/php /usr/local/opnsense/scripts/speedtest/api.php progress
parameters:%s
type:script_output
message:Speedtest progress

[clear]
command:/usr/local/bin/php /usr/local/opnsense/scripts/speedtest/api.php clear
parameters:%s
type:script_output
message:Speedtest clear
