#!/bin/sh
set -eu
control=/usr/local/opnsense/scripts/mihomo/mihomo.py
if [ -n "${PKG_UPGRADE+x}" ]; then
    /usr/local/bin/python3 "$control" suspend
else
    /usr/local/bin/python3 "$control" remove
fi
